# Generated by Django 3.2.18 on 2023-05-02 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='restaurant',
            field=models.CharField(choices=[('TS', 'Tonys'), ('ZT', 'Zaytoons'), ('MR', 'Mercedes'), ('AU', 'Audi')], max_length=100),
        ),
    ]
