# Generated by Django 3.2.18 on 2023-05-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20230502_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='restaurant',
            field=models.CharField(choices=[('Tonys', 'Tonys'), ('Zaytoons', 'Zaytoons'), ('Mercedes', 'Mercedes'), ('Audi', 'Audi')], max_length=100),
        ),
    ]
